### ISSUE TITLE
Error: Too many positional arguments

### ISSUE THREAD

**Issue by tillkruss** [xwp/wp-cli-ssh#19]
When I run: `wp ssh plugin status --host=staging`
I get this error: `Error: Too many positional arguments: status`

This is my project's `wp-cli.yml`:

```
ssh:
    staging:
        cmd: ssh %pseudotty% user@foobar.com %cmd%
        url: staging.foobar.com
        path: /var/www/staging.foobar.com`
```

This is my global `wp-cli.yml`:

```
require:
  - vendor/autoload.php
```

The result of `wp cli info`

```
PHP binary: /usr/bin/php
PHP version:    5.4.24
php.ini used:   /etc/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:   /Users/Foo/.wp-cli/config.yml
WP-CLI project config:  /Users/Foo/Sites/foobar.com/wp-cli.yml
WP-CLI version: 0.16.0
```
