### ISSUE TITLE
wp-cli-ssh not working with Roots.io Trellis & Bedrock 

### ISSUE THREAD

**Issue by jastuccio** [xwp/wp-cli-ssh#24]
I am unable to get wp-cli-ssh working with Roots.io Trellis & Bedrock.  I can use `vagrant ssh` to access the command line in the box.  `wp ssh plugin status --host=vagrant` returns the error ssh: connect to host 192.168.50.10 port 22: Operation timed out.

I installed wp-cli-ssh globally with composer and it is also required in my composer.json file.  This is my wp-cli.local.yml  http://pastebin.com/i9NMXHGE

The path is `path: web/wp` which is standard for Bedrock.  I get errors if I change it to `docroot`

**Comment by retlehs** [comment]
been wanting to try out this project and got it working with @roots:

* add wp-cli-ssh to your project (run this from your vagrant box in the bedrock/`site` directory): `composer require x-team/wp-cli-ssh dev-master`

* edit `wp-cli.yml`:

```yml
path: web/wp

ssh:
  vagrant:
    cmd: cd ../trellis && vagrant ssh-config > /tmp/vagrant_ssh_config && ssh -q %pseudotty% -F /tmp/vagrant_ssh_config default %cmd%
    path: /srv/www/example.com/current/web

  production:
    cmd: ssh %pseudotty% web@example.com %cmd%
    url: roots.io
    path: /srv/www/example.com/current/web
    disabled_commands:
      - db drop
      - db reset
      - plugin install
      - core multisite-convert
```

i haven't found a way of getting this to properly run without passing a full path to `wp-cli-ssh.php`. examples:

```sh
wp ssh plugin status --host=production --require=/Users/ben/Sites/roots/site/vendor/x-team/wp-cli-ssh/wp-cli-ssh.php
```

```sh
wp ssh plugin status --host=vagrant --require=/Users/ben/Sites/roots/site/vendor/x-team/wp-cli-ssh/wp-cli-ssh.php
```

i tried adding `require: vendor/x-team/wp-cli-ssh/wp-cli-ssh.php` to `wp-cli.yml` but that resulted in: 

```sh
PHP Fatal error:  Cannot redeclare class WP_CLI_SSH_Command in /srv/www/example.com/current/vendor/x-team/wp-cli-ssh/wp-cli-ssh.php on line 216
```
